version: '3.9'

services:
  tapgame.api:
    image: tapgameapi:latest
    container_name: tapgame-api
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Sao_Paulo
      ConnectionStrings__DefaultConnection: "server=db;database=tapIdleGame;user=root;password=root;"
    ports:
      - 5151:8080
  # network_mode: "host"
    restart: always
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=root
    restart: always
